global using Kjetil.Demo.DataAccess.Entities;
global using Kjetil.Demo.DataAccess.Infrastructure;
global using Kjetil.Demo.DataAccess.Repositories;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.Linq;
